---
title: "BudweiserCaseStudy"
author: "Kevin Boyd & Scott Frazier"
date: "10/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Budweiser Case Study
## 

### Load Libraries
```{r, message=F}
library(tidyverse)
library(GGally)
library(ggplot2)
library(dplyr)
library(RColorBrewer)
```


### Load in the data
```{r}
beers <- read.csv("beers.csv", header = T)
breweries <- read.csv("breweries.csv", header = T)
```


### Look at the data
```{r}
str(beers)
str(breweries)
head(beers)
head(breweries)
```


### Merge datasets
```{r}
#merge data sets on Brewery_id
names(breweries)[1] <- "Brewery_id"
df1 <- merge(beers, breweries, by = "Brewery_id", all = T)
```


### How many NAs 
```{r - Number 3}
ABV_NAs <- sum(is.na(beers$ABV))
IBU_NAs <- sum(is.na(beers$IBU))
ABV_Total <- NROW(beers$ABV)
IBU_Total <- NROW(beers$IBU)
#make data frame from number of NAs
NA.df1 <- data.frame(Measure = c("ABV","IBU"), Value = c(ABV_NAs,IBU_NAs))

#plot the NA values
ggplot(NA.df1, aes(x=Measure, y=Value)) +
  geom_bar(stat = "identity",fill="#e41a1c") +
  ggtitle("Number of NAs for ABV and IBU") +
  ylab("Number of NAs")
```


### How many breweries in each state
```{r, eval=F}
ggplot(breweries, aes(x= State)) +
  geom_bar(fill="blue") +
  theme(axis.text.x=element_text(angle=90)) +
  ggtitle("Number of Breweries by State") +
  xlab("State") +
  ylab("Count")
```

```{r - Number 1}
#ordered plot
breweries %>%
  group_by(State) %>%
  summarise(count = n()) %>%
  ggplot(aes(x=reorder(State,(-count)), y = count)) +
  geom_bar(stat = "identity",fill="blue") +
  theme(axis.text.x=element_text(angle=90)) +
  ggtitle("Number of Breweries by State") +
  xlab("State") +
  ylab("Count")
```


### Median ABV and IBU values by State
```{r - Number 4}
ABV_Values <- df1 %>% group_by(State) %>%
  summarize(medianABV = median(ABV, na.rm = T)) %>%
  ggplot(aes(x=reorder(State,(-medianABV)), y=medianABV)) +
  geom_bar(stat = "identity", fill="#377eb8") +
  theme(axis.text.x=element_text(angle=90)) +
  ggtitle("Median ABV Values by State") +
  xlab("State") +
  ylab("Median ABV Value")
ABV_Values
```

```{r}
IBU_Values <- df1 %>% group_by(State) %>%
  summarize(medianIBU = median(IBU, na.rm = T)) %>%
  ggplot(aes(x=reorder(State,(-medianIBU)), y=medianIBU)) +
  geom_bar(stat = "identity", fill="#4daf4a") +
  theme(axis.text.x=element_text(angle=90)) +
  ggtitle("Median IBU Values by State") +
  xlab("State") +
  ylab("Median IBU Value")
IBU_Values

```

### Maximum ABV and IBU 
```{r - Number 5}
#make data frames with top 5 
df2 <- df1[order(df1$ABV,decreasing = T),]
df2 <- df2[c(1,2,3,5,6),c(4,10)]
df3 <- df1[order(df1$IBU,decreasing = T),]
df3 <- df3[c(1:5),c(5,10)]
```

```{r}
#plot the top 5 states for IBU
ggplot(df3, aes(x = reorder(State, -IBU), y = IBU)) + 
  geom_bar(stat = "identity", fill = "#4daf4a") +
  ylim(0,150) +
  ggtitle("Top 5 States IBU") +
  xlab("State") +
  geom_text(aes(label=IBU), vjust=-1) +
  ylab("International bitterness units of beer (IBU)")
```

```{r}
#plot the top states for ABV
ggplot(df2, aes(x = reorder(State, -ABV), y = ABV)) + 
  geom_bar(stat = "identity", fill= "#377eb8") +
  ylim(0,0.15) +
  ggtitle("Top 5 States ABV") +
  xlab("State") +
  geom_text(aes(label=ABV), vjust=-1) +
  ylab("Alcohol by volume of beer (ABV)")
```



```{r - Number 6}
#Summary stats of ABV
summary(df1$ABV)

###Distributions
#Histogram of ABV in df1 - looks decent
df1 %>% ggplot(aes(x=ABV)) + geom_histogram(fill = "#377eb8") + ggtitle("Distribution of Alcohol by volume of the beer (ABV)") + labs(x="Alcohol by volume of the beer (ABV)", y="Frequency")

#boxplot - might need some work
df1 %>% ggplot(aes(x=ABV)) + geom_boxplot(fill = "#377eb8") + ggtitle("Distribution of Alcohol by volume of the beer (ABV)") + labs(x="Alcohol by volume of the beer (ABV)", y="") + coord_flip()


#geom_density - looks decent
ABV_vizz = ggplot(df1, aes(x = ABV))

ABV_vizz + geom_density(fill = "#377eb8", alpha=0.6) +
  geom_vline(aes(xintercept = mean(ABV)), 
             linetype = "dashed", size = 0.6,
             color = "#FC4E07") +
  ylab("Frequency") +
  ggtitle("Distribution of All ABV Values") +
  xlab("Alcohol by volume of the beer (ABV)")
```



```{r - Number 7}
ggplot(df1, aes(x=ABV, y=IBU)) +
  geom_point() +
  geom_jitter() +
  geom_smooth() +
  ggtitle("ABV vs IBU")


```




```{r - map}
#This is the website I am trying to follow to create a map of the states showing the number of breweries in each state

#https://cran.r-project.org/web/packages/usmap/vignettes/mapping.html

library(usmap)
library(maps)
library(ggplot2)

#This is from the website, shows states
plot_usmap(data = statepop, values = "pop_2015", color = "red") + 
  scale_fill_continuous(name = "Population (2015)", label = scales::comma) + 
  theme(legend.position = "right")

```





